@startuml 001_RequestingNetconfInterface
skinparam responseMessageBelowArrow true

title
RequestForMountingDeviceCausesRequestingNetconfInterface
end title

participant "APTP" as APTP
participant "MO://v1/mount-device" as MO
participant "MM://v1/provide-netconf-interface" as MM


APTP -> MO: {deviceType, manufacturerName, deviceIp, mountName} (apiKeyAuth)

MO -> MM: {deviceType, manufacturerName, deviceIp, mountName} (apiKeyAuth)

MM --> MO: 200: {mountName, netconfInterfaceIpAddress, NetconfPort} (apiKeyAuth)


@enduml