@startuml 005_PreparingConnection
skinparam responseMessageBelowArrow true

participant "APTP" as APTP
participant "APTP://v1/receive-outcome-of-mounting-request" as APTP_receive
participant "MO://v1/mount-device" as MO
participant "   CP://v1/prepare-connection-at-ericsson-traffic-node\nor    CP://v1/prepare-connection-at-ericsson-ml6352\nor    CP://v1/prepare-connection-at-ericsson-ml6600\nor    CP://v1/prepare-connection-at-huawei\nor    CP://v1/prepare-connection-at-siae-alcp2e\nor    CP://v1/prepare-connection-at-siae-ags20\nor    CP://v1/prepare-connection-at-siae-alfo80" as CP


APTP -> MO: {mountName, deviceType, deviceIp} (apiKeyAuth)

activate MO

group Validate, whether deviceType is known
  note over MO
    IF the {deviceType} is not found among the existing instances of the DeviceTypeProfile
    **/core-model-1-4:control-construct/profile-collection/profile=mo-1-0-0-device-p-xxx/device-profile-1-0:device-profile-pac/device-profile-capability/device-type**
  end note
  MO --> APTP: 406: Not Acceptable  
  note right #Salmon
    [would it create benefit, if the message would be more explicit
    (e.g. identifying that the value of the deviceType attribute was unknown to the application)]
  end note
end group

group Validate, whether device can be reached
  note over MO
    Perform number of ping tests according to
    **/core-model-1-4:control-construct/profile-collection/profile=mo-1-0-0-integer-p-000/integer-profile-1-0:integer-profile-pac/integer-profile-configuration/integer-value**
    IF a single ping test failed
  end note
  MO --> APTP: ???: ??? (device could not be pinged)
  note over MO
    Perform potentially an additional connection test (depending on DeviceTypeCapability defined in the DeviceTypeProfile):
    **/core-model-1-4:control-construct/profile-collection/profile=mo-1-0-0-device-p-xxx/device-profile-1-0:device-profile-pac/device-profile-capability/snmp-test-required**
    **/core-model-1-4:control-construct/profile-collection/profile=mo-1-0-0-device-p-xxx/device-profile-1-0:device-profile-pac/device-profile-capability/https-test-required**
    [test of the Qx at Huawei is missing]
    IF protocol test failed
  end note
  MO --> APTP: ???: ??? (management protocol layer testing failed)
end group

MO --> APTP: 202: Request Accepted {requestId}

group Initiate preparation of the device
  note over MO
    Call ConnectionPreparation (CP) service according to DeviceTypeProfile configuration
    **/core-model-1-4:control-construct/profile-collection/profile=mo-1-0-0-device-p-xxx/device-profile-1-0:device-profile-pac/device-profile-configuration/connection-preparation-service**
  end note
  MO -> CP: {deviceIp} (apiKeyAuth)
  CP --> MO: 204 / ???
end group

MO -> APTP_receive: {requestId, mountingOutcome} (apiKeyAuth)