@startuml 021_CallingDeviceOnController
skinparam responseMessageBelowArrow true

title
RequestForMountingDeviceCausesCallingDeviceOnController
end title

participant "APTP" as APTP
participant "MO://v1/mount-device" as MO
participant "ODL://{controllerInternalPathToMountPoint}/node={mountName}/yang-ext:mount/core-model-1-4:control-construct" as ODL 


APTP -> MO: {deviceType, manufacturerName, deviceIp, mountName} (apiKeyAuth)

MO -> ODL: {mountName} (apiKeyAuth)

ODL --> MO: {ControlConstruct}

deactivate MO

@enduml